Easypeasy.Parent = DS.Model.extend
  name:                                   DS.attr 'string'
  first_name:                             DS.attr 'string'
  pod_name:                               DS.attr 'string'
  pod_active:                             DS.attr 'boolean'
  slug:                                   DS.attr 'string'
  pod_most_recent_comment_notice:         DS.attr 'string'
  first_visit:                            DS.attr 'boolean'
  pod_played_current_game:                DS.attr 'string'
