development:
  adapter: postgresql
  encoding: unicode
  database: easypeasy_development
  username: basil
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: easypeasy_test
  pool: 5
  username: basil
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: easypeasy_production
  pool: 5
  username: easypeasy
